name: Deploy

'on':
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - 'tutorials-build' # triggered from astropy/astropy-tutorials

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.node_version.outputs.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.node_version.outputs.NODE_VERSION }}

      - run: npm ci
        name: Install

      - run: npm run build
        name: Build

      - name: Upload gatsby artifact
        uses: actions/upload-artifact@v3
        with:
          name: gatsby-build
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r deployment/requirements.txt

      - name: Download gatsby artifact
        uses: actions/download-artifact@v2
        with:
          name: gatsby-build
          path: ./public

      - name: Download tutorials for tutorial dispatch event
        if: ${{ github.event == 'repository_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python deployment/installtutorials.py \
            --dest public/tutorials \
            --tutorials-run ${{ github.event.client_payload.runid }} \
            --tutorials-artifact ${{ github.event.client_payload.artifactName }} \
            --tutorials-repo ${{ github.event.client_payload.repo }}

      - name: Download latest tutorials
        if: ${{ github.event != 'repository_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python deployment/installtutorials.py --dest public/tutorials

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Index tutorials
        env:
          ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
        run: |
          astropylibrarian index tutorial-site \
            public/tutorials \
            https://learn.astropy.org/tutorials
